export enum Colors {
    light = 'light',
    dark = 'dark',
    grey1 = 'grey1',
    grey2 = 'grey2',
    grey3 = 'grey3',
    grey4 = 'grey4',
    asphalt1 = 'asphalt1',
    asphalt2 = 'asphalt2',
    asphalt3 = 'asphalt3',
    asphalt4 = 'asphalt4',
    asphalt5 = 'asphalt5',
    asphalt6 = 'asphalt6',
    asphalt7 = 'asphalt7',
    atlantis1 = 'atlantis1',
    atlantis2 = 'atlantis2',
    atlantis3 = 'atlantis3',
    atlantis4 = 'atlantis4',
    atlantis5 = 'atlantis5',
    blue1 = 'blue1',
    blue2 = 'blue2',
    blue3 = 'blue3',
    blue4 = 'blue4',
    blue5 = 'blue5',
    red1 = 'red1',
    red2 = 'red2',
    red3 = 'red3',
    red4 = 'red4',
    red5 = 'red5',
    yellow1 = 'yellow1',
    yellow2 = 'yellow2',
    yellow3 = 'yellow3',
    yellow4 = 'yellow4',
    yellow5 = 'yellow5',
    purple1 = 'purple1',
    purple2 = 'purple2',
    purple3 = 'purple3',
    purple4 = 'purple4'
}

export const ColorNames = Object.keys(Colors).map((key: string) => key);
