import { SSSTable as TableComponent } from "./components/table";
import { SSSButton as ButtonComponent } from "./components/button";
import { SSSAlert as AlertComponent } from "./components/alert";
import { SSSTabs as TabsComponent } from "./components/tabs";
import { SSSPagination as PaginationComponent } from "./components/pagination";
import { SSSBadge as BadgeComponent } from "./components/badge";
import { SSSLeadingBadge as LeadingBadgeComponent } from "./components/leading-badge";
import { SSSModal as ModalComponent } from "./components/modal";
import { SSSBreadcrumbs as BreadcrumbsComponent } from "./components/breadcrumbs";
import { SSSCheckbox as CheckboxComponent } from "./components/checkbox";
import { SSSDivider as DividerComponent } from "./components/divider";
import { SSSSwitch as SwitchComponent } from "./components/switch-toggle";
import { SSSTypography as TypographyComponent } from "./components/typography";
import { SSSDropdown as DropdownComponent } from "./components/dropdown";
import { SSSInput as InputComponent } from "./components/input";
import { SSSTooltip as TooltipComponent } from "./components/tooltip";
import { SSSFileUpload as FileUploadComponent } from "./components/file-upload";
import { SSSAccordion as AccordionComponent } from "./components/accordion";
import { SSSHeader as HeaderComponent } from "./components/header";
import { SSSFooter as FooterComponent } from "./components/footer";
import { SSSDatepicker as DatepickerComponent } from "./components/date-picker";
import { SSSSidebar as SidebarComponent } from "./components/sidebar";
import { Theme as SSSTheme } from "./shared/theme";
import { Constants as Const } from "./services";

export const Button = ButtonComponent;
export const Alert = AlertComponent;
export const Tabs = TabsComponent;
export const Table = TableComponent;
export const Pagination = PaginationComponent;
export const Badge = BadgeComponent;
export const LeadingBadge = LeadingBadgeComponent;
export const Modal = ModalComponent;
export const Breadcrumbs = BreadcrumbsComponent;
export const Checkbox = CheckboxComponent;
export const Divider = DividerComponent;
export const Switch = SwitchComponent;
export const Typography = TypographyComponent;
export const Dropdown = DropdownComponent;
export const Input = InputComponent;
export const Tooltip = TooltipComponent;
export const FileUpload = FileUploadComponent;
export const Accordion = AccordionComponent;
export const Header = HeaderComponent;
export const Footer = FooterComponent;
export const Datepicker = DatepickerComponent;
export const Sidebar = SidebarComponent;
export const Theme = SSSTheme;
export const Constants = Const;

export * from "./components/icons";
export * from "./components/logos";
export * from "./services";
export * from "./types";
