# This is a basic workflow to help you get started with Actions

name: PR to master

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            password: ${{secrets.SSH_PASSPHRASE}}
            script: |
              cd /var/www/vhosts/oykos.me/devkit.oykos.me
              [ -d "./pr" ] && echo "Existing pr directory" || mkdir pr
              cd pr
              rm -rf ./${{secrets.GIT_REPO}}
              git clone https://oykos-development-hub:${{secrets.GIT_ACCESS_TOKEN}}@github.com/oykos-development-hub/${{secrets.GIT_REPO}}.git
              cd ./${{secrets.GIT_REPO}}
              npm install husky
              npm install
              npm run git:pull-request
              cd ../../
              rm -rf pr
