# This is a basic workflow to help you get started with Actions

name: Deploy to production server

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            password: ${{secrets.SSH_PASSPHRASE}}
            script: |
              cd /var/www/vhosts/oykos.me/devkit.oykos.me
              [ -d "./github" ] && echo "Existing github directory" || mkdir github
              cd github
              rm -rf ./${{secrets.GIT_REPO}}
              git clone https://oykos-development-hub:${{secrets.GIT_ACCESS_TOKEN}}@github.com/oykos-development-hub/${{secrets.GIT_REPO}}.git
              cd ./${{secrets.GIT_REPO}}
              npm install husky
              npm install
              storybook:production
              cp -R ./storybook-docs/** ../../
              npm config set _authToken=${{secrets.NPM_TOKEN}}
              npm publish --access public
